Test of the workflow-template for github actions
Artx999/klinks pull request #13
Opened 2023-03-31 11:02 UTC by Markhauk

Testing the basic template file for github workflow.

2023-04-02 19:50 UTC, Artx999 requested changes
This should be merged with dev, not main.

2023-04-13 11:50 UTC, adrian9991 approved these changes
nice

2023-04-14 12:04 UTC, adrian9991 approved these changes

2023-05-12 16:40 UTC, Markhauk commented
Setting up a new one. This was just a test

2023-05-12 16:40 UTC, closed without merging